version: '3.8'

services:
    postgres:
        image: postgres:17.4-alpine
        container_name: devbrain-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-devbrain}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '${POSTGRES_PORT:-5433}:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres-data:
